config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show] do
    post 'invite', on: :member, to: 'users#invite'
    post 'attend', on: :member, to: 'users#attend'
  end

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#login'
  delete 'logout', to: 'sessions#logout'
  resources :events, only: [:new, :create, :show, :index]
  root 'events#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  has_many :attendances, foreign_key: 'attended_event_id'
  has_many :attendees, through: :attendances, source: :attendee
  has_many :invitations, foreign_key: 'inviting_event_id'
  has_many :inviteds, through: :invitations, source: :invited
  scope :past, -> { where('date < ?', Time.now.to_date) }
  scope :future, -> { where('date > ?', Time.now.to_date) }
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :invited, class_name: 'User'
  belongs_to :inviting_event, class_name: 'Event'
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :attended_events, through: :attendances, source: :attended_event
  has_many :invitations, foreign_key: 'invited_id'
  has_many :inviting_events, through: :invitations, source: :inviting_event

  def upcoming_attended_events
    attended_events.where('date > ?', Time.now.to_date)
  end

  def past_attended_events
    attended_events.where('date < ?', Time.now.to_date)
  end

  def invite(user, event)
    event.inviteds << user unless event.inviteds.include?(user)
  end

  def attend(event)
    attended_events << event unless attended_events.include?(event)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @attendees = @event.attendees
  end

  def index
    @events = Event.all
    @past_events = Event.past
    @future_events = Event.future
  end

  def create
    @user = User.find(session[:user_id])
    @event = @user.events.build(event_params)

    if @event.save
      redirect_to event_url(@event)
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:description, :date)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def login
    @user = User.find_by(name: params[:name])

    if @user
      redirect_to root_url
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def logout
    session.delete(:user_id)
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_url(@user)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @attended_events = @user.attended_events
    @upcoming_attended_events = @user.upcoming_attended_events
    @past_attended_events = @user.past_attended_events
  end

  def invite
    @user = User.find(params[:id])
    @event = Event.find(params[:event_id])
    inviteds = params[:invitation][:users].strip.split(',').map(&:strip)

    inviteds.each do |invited|
      user = User.find_by(name: invited)
      @user.invite(user, @event) if user
    end

    redirect_to event_url(@event)
  end

  def attend
    @user = User.find(params[:id])
    @event = Event.find(params[:event_id])

    @user.attend(@event) if @event.inviteds.include?(@user)

    redirect_to user_url(@user)
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def logged_in?
    !controller.session[:user_id].nil?
  end

  def current_user
    logged_in? ? User.find(controller.session[:user_id]) : nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h2>All events</h2>
<ul>
  <% @events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>

<h2>Past events</h2>
<ul>
  <% @past_events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>

<h2>Future events</h2>
<ul>
  <% @future_events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>

app/views/events/new.html.erb
<%= form_for(@event) do |f| %>
  <div><%= f.label :description %></div>
  <div><%= f.text_area :description %></div>
  <div><%= f.label :date %></div>
  <div><%= f.date_field :date %></div>
  <%= f.submit %>
<% end %>

app/views/events/show.html.erb
<h2>Description</h2>
<p><%= @event.description %></p>

<h2>Date</h2>
<p><%= @event.date %></p>

<h2>Creator</h2>
<p>
<strong>creator</strong>: <%= @event.creator.name %> |
<%= link_to 'Show', user_path(@event.creator) %>
</p>

<h2>Attendees</h2>
<ul>
  <% @attendees.each do |attendee| %>
    <li><%= attendee.name %> | <%= link_to 'Show', user_path(attendee) %></li>
  <% end %>
</ul>

<% if current_user && current_user == @event.creator %>
  <%= form_tag(invite_user_path(@event.creator)) do %>
    <%= hidden_field_tag :event_id, "#{@event.id}" %>
    <%= fields :invitation do |f| %>
      <div><%= f.label :users, 'Users to invite' %></div>
      <div><%= f.text_field :users, placeholder: 'jen, bob, stuart', id: 'invitation_users' %></div>
    <% end %>
    <%= submit_tag 'Invite' %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEventsSmall</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if current_user %>
        <%= current_user.name %> |
        <%= link_to 'Profile', user_path(current_user) %> |
        <%= link_to 'Logout', logout_path, method: :delete %> |
        <%= link_to 'Create event', new_event_path %> |
      <% else %>
        <%= link_to 'Sign up', new_user_path %> |
        <%= link_to 'Login', login_path %> |
      <% end %>
      <%= link_to 'Events', events_path %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <div><%= f.label :name %></div>
  <div><%= f.text_field :name %></div>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<% if current_user && current_user == @user %>
  <h2>Invitations</h2>
  <ul>
    <% @user.inviting_events.each do |event| %>
      <li>
        <%= event.description %> |
        <%= link_to 'Attend', attend_user_path(id: @user.id, event_id: event.id), method: :post %>
      </li>
    <% end %>
  </ul>
<% end %>

<h2>All created events</h2>
<ul>
  <% @user.events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>

<h2>All attended events</h2>
<ul>
  <% @attended_events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>

<h2>Past attended events</h2>
<ul>
  <% @past_attended_events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>

<h2>Upcoming events to attend</h2>
<ul>
  <% @upcoming_attended_events.each do |event| %>
    <li><%= event.description %> | <%= link_to 'Show', event_path(event) %></li>
  <% end %>
</ul>